name: Build and Publish
on:
  push:
    branches: ['master']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar JDK
        uses: actions/setup-java@v4
        with:
          java-version: 25
          distribution: 'temurin'
          architecture: 'x64'
          cache: maven

      - name: Executar testes com Maven
        run: mvn test
